<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Native AOT for publish only; no effect on dotnet run/build -->
    <PublishAot>true</PublishAot>
    <TrimMode>full</TrimMode>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

</Project>
